### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by cryptax** [Ch0pin/medusa#29]
On Linux, I got this error "No module named 'readline'" when launching `medusa.py`. It can be solved by adding `readline` to the list of `requirements.txt`.

Error:
```
$ python3 medusa.py 
Readline features including tab completion have been disabled because
no supported version of readline was found. To resolve this, install
pyreadline on Windows or gnureadline on Mac.

Traceback (most recent call last):
  File "/home/axelle/softs/medusa/medusa.py", line 6, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```
Quick Solution: `pip3 install readline`.
Better solution: add it to `requirements.txt`

**Comment by Ch0pin** [comment]
Done @cryptax , thanks !

**Comment by cryptax** [comment]
I think there is a typo: `readline 6.2.4.2` does not exist (?). Did you mean `readline==6.2.4` ?

```
ERROR: Could not find a version that satisfies the requirement readline==6.2.4.2 (from -r requirements.txt (line 3)) (from versions: 2.4.2, 2.5.1, 2.6.1, 2.6.4, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 6.2.4, 6.2.4.1)
```

Also you removed `google_trans_new` from `requirements.txt` but it is needed:

```
!523]$ python3 medusa.py 
Traceback (most recent call last):
  File "medusa.py", line 11, in <module>
    from google_trans_new import google_translator  
ModuleNotFoundError: No module named 'google_trans_new'
```
