### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by blap** [Ch0pin/medusa#3]
python medusa.py
`Traceback (most recent call last):
  File "C:\Users\Bruno Pio\Desktop\medusa-master\medusa.py", line 6, in <module>
    from libraries.defs import *
  File "C:\Users\Bruno Pio\Desktop\medusa-master\libraries\defs.py", line 16, in <module>
    if 'libedit' in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable`

python apkutils.py
`  File "C:\Users\Bruno Pio\Desktop\medusa-master\apkutils.py", line 9, in <module>
    import pty
  File "C:\Program Files\Python\lib\pty.py", line 12, in <module>
    import tty
  File "C:\Program Files\Python\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'`

**Comment by Ch0pin** [comment]
https://github.com/bchao1/bullet/issues/2
