### ISSUE TITLE
mango.py No module named '_bz2'

### ISSUE THREAD

**Issue by cryptax** [Ch0pin/medusa#30]
Mango does not launch. This is running from a Python virtual environment where I did `pip3 install -r requirements.txt`
I have python 3.10

```
$ python3 mango.py 
Traceback (most recent call last):
  File "/home/axelle/softs/medusa/mango.py", line 1, in <module>
    from androguard.misc import AnalyzeAPK
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/androguard/misc.py", line 1, in <module>
    from androguard.session import Session
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/androguard/session.py", line 5, in <module>
    from androguard.core.analysis.analysis import Analysis
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/androguard/core/analysis/analysis.py", line 11, in <module>
    import networkx as nx
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/networkx/__init__.py", line 59, in <module>
    from networkx import utils
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/networkx/utils/__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "/home/axelle/softs/medusa/venv/lib/python3.10/site-packages/networkx/utils/decorators.py", line 1, in <module>
    import bz2
  File "/usr/local/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

This is `pip3 list`:

```
$ pip3 list
Package           Version
----------------- ---------
androguard        3.3.5
asn1crypto        1.5.1
asttokens         2.1.0
attrs             22.1.0
backcall          0.2.0
certifi           2022.9.24
chardet           4.0.0
click             8.0.3
cmd2              2.3.3
colorama          0.4.4
contourpy         1.0.6
cycler            0.11.0
decorator         5.1.1
executing         1.2.0
fonttools         4.38.0
frida             15.1.13
future            0.18.2
google-trans-new  1.1.9
idna              2.10
ipython           8.6.0
jedi              0.18.1
kiwisolver        1.4.4
lxml              4.9.1
matplotlib        3.6.2
matplotlib-inline 0.1.6
networkx          2.8.8
numpy             1.23.4
packaging         21.3
parso             0.8.3
pexpect           4.8.0
pickleshare       0.7.5
Pillow            9.3.0
pip               22.3.1
prompt-toolkit    3.0.32
ptyprocess        0.7.0
pure-eval         0.2.2
pydot             1.4.2
Pygments          2.13.0
pyparsing         3.0.9
pyperclip         1.8.2
python-dateutil   2.8.2
readline          6.2.4.1
requests          2.25.1
setuptools        58.1.0
six               1.16.0
stack-data        0.6.1
traitlets         5.5.0
urllib3           1.26.12
wcwidth           0.2.5
```

**Comment by Ch0pin** [comment]
It seems more like an issue with the python version you are using

**Comment by cryptax** [comment]
Yes, you are right. It works just fine with Python **3.8.**
