### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mriamnobody** [Ch0pin/medusa#41]
I'm on windows 11, Python version 3.10.7. Created `venv` and got no error while `pip install -r requirements.txt`

`Traceback (most recent call last):
  File "C:\Users\auser\Downloads\Compressed\medusa-master\medusa.py", line 1431, in <module>
    if 'libedit' in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by mriamnobody** [comment]
@Ch0pin

**Comment by mriamnobody** [comment]
I tried installing the pyreadline which resulted in another error:

`Traceback (most recent call last):
  File "C:\Users\auser\Downloads\Compressed\medusa-master\medusa.py", line 2, in <module>
    import subprocess, platform, os, sys, readline, time, argparse
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\auser\Downloads\Compressed\medusa-master\myenv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'`

**Comment by mriamnobody** [comment]
Initially, when I ran the medusa.py I received the error:

`Traceback (most recent call last):
  File "C:\Users\auser\Downloads\Compressed\medusa-master\medusa.py", line 2, in <module>
    import subprocess, platform, os, sys, readline, time, argparse
ModuleNotFoundError: No module named 'readline'`

**Comment by Ch0pin** [comment]
@mriamnobody, Medusa officially doesn't support windows. But you can try the "develop" branch since we started porting it there. For the moment when it comes to windows you can use (without any issue) windows subsystem for linux (wsl).
