### ISSUE TITLE
Installlation error 

### ISSUE THREAD

**Issue by silentknight46** [Ch0pin/medusa#84]
Hello 

First I got this error 
`C:\Users\Hoxar46\Downloads\medusa-master\medusa-master>python3 medusa.py
Traceback (most recent call last):
  File "C:\Users\Hoxar46\Downloads\medusa-master\medusa-master\medusa.py", line 1997, in <module>
    if 'libedit' in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable`

I tried to install  pyreadline as per your suggestion  after this i got below error 

My python version 
`C:\Users\Hoxar46\Downloads\medusa-master\medusa-master>python3 --version
Python 3.10.11`

`C:\Users\Hoxar46\Downloads\medusa-master\medusa-master>python3 medusa.py
Traceback (most recent call last):
  File "C:\Users\Hoxar46\Downloads\medusa-master\medusa-master\medusa.py", line 2, in <module>
    import subprocess, platform, os, sys, readline, time, argparse, requests, re
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\Hoxar46\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
`

**Comment by Ch0pin** [comment]
@silentknight46 , medusa doesn't support windows yet. You can probably use docker as an alternative (check the Dockerfile for further details).
